[pytest]
pythonpath = .
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
testpaths = tests
env =
    DATABASE_URL=sqlite+aiosqlite:///:memory:
    SECRET_KEY=TEST_SECRET_KEY
    ALGORITHM=HS256
    ACCESS_TOKEN_EXPIRE_MINUTES=60
