"""add_actividad_dependencias

Revision ID: 071dbf6154e5
Revises: f4324ce37e41
Create Date: 2026-08-29 17:30:17.368063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '071dbf6154e5'
down_revision: Union[str, None] = 'f4324ce37e41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividades_dependencias',
    sa.Column('predecesora_id', sa.Integer(), nullable=False),
    sa.Column('sucesora_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['predecesora_id'], ['actividades_cronograma.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sucesora_id'], ['actividades_cronograma.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('predecesora_id', 'sucesora_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actividades_dependencias')
    # ### end Alembic commands ###
