"""Add cost breakdown to PartidaPresupuesto

Revision ID: 0f31cde54c43
Revises: 7b94f6c204ad
Create Date: 2026-08-29 01:55:53.750656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f31cde54c43'
down_revision: Union[str, None] = '7b94f6c204ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partidas_presupuesto', sa.Column('coste_base', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('partidas_presupuesto', sa.Column('coste_material', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('partidas_presupuesto', sa.Column('porcentaje_indirectos', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('partidas_presupuesto', sa.Column('porcentaje_comisiones', sa.Numeric(precision=5, scale=2), nullable=True))
    op.alter_column('partidas_presupuesto', 'cantidad',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('partidas_presupuesto', 'coste_unitario',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
    op.alter_column('partidas_presupuesto', 'precio_unitario',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('partidas_presupuesto', 'descuento_porcentaje',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=5, scale=2),
               nullable=True)
    op.alter_column('partidas_presupuesto', 'margen_porcentaje',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=5, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partidas_presupuesto', 'margen_porcentaje',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('partidas_presupuesto', 'descuento_porcentaje',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('partidas_presupuesto', 'precio_unitario',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('partidas_presupuesto', 'coste_unitario',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('partidas_presupuesto', 'cantidad',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('partidas_presupuesto', 'porcentaje_comisiones')
    op.drop_column('partidas_presupuesto', 'porcentaje_indirectos')
    op.drop_column('partidas_presupuesto', 'coste_material')
    op.drop_column('partidas_presupuesto', 'coste_base')
    # ### end Alembic commands ###
