"""make codigo unique per empresa

Revision ID: 39b45759fca1
Revises: 04dbf5b9acb2
Create Date: 2026-09-29 20:42:23.713449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39b45759fca1'
down_revision: Union[str, None] = '04dbf5b9acb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eventos_actividad')
    op.drop_table('eventos_actividad_lecturas')
    op.drop_index(op.f('ix_obras_codigo'), table_name='obras')
    op.create_index(op.f('ix_obras_codigo'), 'obras', ['codigo'], unique=False)
    op.create_unique_constraint('uix_obra_codigo_empresa', 'obras', ['codigo', 'empresa_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_obra_codigo_empresa', 'obras', type_='unique')
    op.drop_index(op.f('ix_obras_codigo'), table_name='obras')
    op.create_index(op.f('ix_obras_codigo'), 'obras', ['codigo'], unique=1)
    op.create_table('eventos_actividad_lecturas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('evento_id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=False),
    sa.Column('leido_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos_actividad.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventos_actividad',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tipo_evento', sa.VARCHAR(length=50), nullable=False),
    sa.Column('mensaje', sa.VARCHAR(length=500), nullable=False),
    sa.Column('empresa_id', sa.INTEGER(), nullable=False),
    sa.Column('entidad_relacionada_tipo', sa.VARCHAR(length=50), nullable=True),
    sa.Column('entidad_relacionada_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
