"""esquema completo v3

Revision ID: 412e888226df
Revises: 
Create Date: 2026-08-10 20:35:54.297199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '412e888226df'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('rol', sa.Enum('ADMIN', 'INSPECTOR', name='rolusuario'), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('invitaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'ACEPTADA', 'EXPIRADA', name='estadoinvitacion'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expira_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitaciones_email'), 'invitaciones', ['email'], unique=False)
    op.create_index(op.f('ix_invitaciones_token'), 'invitaciones', ['token'], unique=True)
    op.create_table('obras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('cliente', sa.String(length=200), nullable=True),
    sa.Column('direccion', sa.String(length=300), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'EN_EJECUCION', 'EN_PAUSA', 'FINALIZADA', 'ENTREGADA', 'ARCHIVADA', name='estadoobra'), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('superficie_m2', sa.Float(), nullable=True),
    sa.Column('progreso_porcentaje', sa.Integer(), nullable=True),
    sa.Column('estado_actual_texto', sa.String(length=200), nullable=True),
    sa.Column('chat_id_telegram', sa.String(length=50), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obras_codigo'), 'obras', ['codigo'], unique=True)
    op.create_table('perfiles_empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre_empresa', sa.String(length=200), nullable=False),
    sa.Column('logo_ruta', sa.String(length=500), nullable=True),
    sa.Column('color_principal', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('citas_visita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=True),
    sa.Column('nombre_referencia', sa.String(length=200), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'COMPLETADA', 'CANCELADA', name='estadocita'), nullable=False),
    sa.Column('recordatorio_minutos_antes', sa.Integer(), nullable=True),
    sa.Column('momento_recordatorio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recordatorio_enviado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('obra_id IS NOT NULL OR nombre_referencia IS NOT NULL', name='ck_cita_obra_o_referencia'),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citas_visita_momento_recordatorio'), 'citas_visita', ['momento_recordatorio'], unique=False)
    op.create_index(op.f('ix_citas_visita_obra_id'), 'citas_visita', ['obra_id'], unique=False)
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.Enum('PLANOS', 'PRESUPUESTOS', 'CONTRATOS', 'FACTURAS', 'GARANTIAS', 'TECNICA', name='categoriadocumento'), nullable=False),
    sa.Column('nombre_original', sa.String(length=255), nullable=False),
    sa.Column('ruta_archivo', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_obra_id'), 'documentos', ['obra_id'], unique=False)
    op.create_table('visitas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitas_obra_id'), 'visitas', ['obra_id'], unique=False)
    op.create_table('visita_archivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visita_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('FOTO', 'VIDEO', name='tipoarchivovisita'), nullable=False),
    sa.Column('ruta_archivo', sa.String(length=500), nullable=False),
    sa.Column('nombre_original', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['visita_id'], ['visitas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visita_archivos_visita_id'), 'visita_archivos', ['visita_id'], unique=False)
    op.create_table('visitas_potenciales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cita_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cita_id'], ['citas_visita.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitas_potenciales_cita_id'), 'visitas_potenciales', ['cita_id'], unique=False)
    op.create_table('visita_potencial_archivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visita_potencial_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('FOTO', 'VIDEO', name='tipoarchivovisita'), nullable=False),
    sa.Column('ruta_archivo', sa.String(length=500), nullable=False),
    sa.Column('nombre_original', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['visita_potencial_id'], ['visitas_potenciales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visita_potencial_archivos_visita_potencial_id'), 'visita_potencial_archivos', ['visita_potencial_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visita_potencial_archivos_visita_potencial_id'), table_name='visita_potencial_archivos')
    op.drop_table('visita_potencial_archivos')
    op.drop_index(op.f('ix_visitas_potenciales_cita_id'), table_name='visitas_potenciales')
    op.drop_table('visitas_potenciales')
    op.drop_index(op.f('ix_visita_archivos_visita_id'), table_name='visita_archivos')
    op.drop_table('visita_archivos')
    op.drop_index(op.f('ix_visitas_obra_id'), table_name='visitas')
    op.drop_table('visitas')
    op.drop_index(op.f('ix_documentos_obra_id'), table_name='documentos')
    op.drop_table('documentos')
    op.drop_index(op.f('ix_citas_visita_obra_id'), table_name='citas_visita')
    op.drop_index(op.f('ix_citas_visita_momento_recordatorio'), table_name='citas_visita')
    op.drop_table('citas_visita')
    op.drop_table('perfiles_empresa')
    op.drop_index(op.f('ix_obras_codigo'), table_name='obras')
    op.drop_table('obras')
    op.drop_index(op.f('ix_invitaciones_token'), table_name='invitaciones')
    op.drop_index(op.f('ix_invitaciones_email'), table_name='invitaciones')
    op.drop_table('invitaciones')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
