"""Add Cuaderno de Obra

Revision ID: 43da4dd16cc1
Revises: ae103338c776
Create Date: 2026-09-06 18:49:26.749832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43da4dd16cc1'
down_revision: Union[str, None] = 'ae103338c776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notas_cuaderno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('tipo', sa.Enum('NOTA', 'CROQUIS', 'VISITA', 'TAREA', 'INCIDENCIA', 'PRESUPUESTO', 'CERTIFICACION', 'PEDIDO', 'OTRO', name='tiponotacuaderno'), nullable=False),
    sa.Column('canvas_data', sa.JSON(), nullable=True),
    sa.Column('preview_url', sa.String(length=500), nullable=True),
    sa.Column('entidad_relacionada_tipo', sa.String(length=50), nullable=True),
    sa.Column('entidad_relacionada_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notas_cuaderno_obra_id'), 'notas_cuaderno', ['obra_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notas_cuaderno_obra_id'), table_name='notas_cuaderno')
    op.drop_table('notas_cuaderno')
    # ### end Alembic commands ###
