"""Add VENCIDA and TareaArchivo

Revision ID: 525014512f53
Revises: 93a5248b0adf
Create Date: 2026-08-27 14:17:23.417232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '525014512f53'
down_revision: Union[str, None] = '93a5248b0adf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Agregado manualmente:
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        with op.get_context().autocommit_block():
            op.execute("ALTER TYPE estadotarea ADD VALUE IF NOT EXISTS 'VENCIDA'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tareas_archivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tarea_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('FOTO', 'VIDEO', 'DOCUMENTO', name='tipoarchivotarea'), nullable=False),
    sa.Column('nombre_original', sa.String(length=255), nullable=False),
    sa.Column('ruta_archivo', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tarea_id'], ['tareas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tareas_archivos_tarea_id'), 'tareas_archivos', ['tarea_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tareas_archivos_tarea_id'), table_name='tareas_archivos')
    op.drop_table('tareas_archivos')
    # ### end Alembic commands ###
