"""add_company_details

Revision ID: 5a8989b8b7b5
Revises: d00bac3595b1
Create Date: 2026-08-29 11:47:15.872397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a8989b8b7b5'
down_revision: Union[str, None] = 'd00bac3595b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perfiles_empresa', sa.Column('direccion', sa.String(length=300), nullable=True))
    op.add_column('perfiles_empresa', sa.Column('telefono', sa.String(length=50), nullable=True))
    op.add_column('perfiles_empresa', sa.Column('correo', sa.String(length=150), nullable=True))
    op.add_column('perfiles_empresa', sa.Column('cif', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('perfiles_empresa', 'cif')
    op.drop_column('perfiles_empresa', 'correo')
    op.drop_column('perfiles_empresa', 'telefono')
    op.drop_column('perfiles_empresa', 'direccion')
    # ### end Alembic commands ###
