"""Add subchapters and budget fields

Revision ID: 7b94f6c204ad
Revises: c07c89447746
Create Date: 2026-08-29 01:19:50.310445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b94f6c204ad'
down_revision: Union[str, None] = 'c07c89447746'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capitulos_presupuesto', sa.Column('padre_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'capitulos_presupuesto', 'capitulos_presupuesto', ['padre_id'], ['id'], ondelete='CASCADE')
    op.add_column('partidas_presupuesto', sa.Column('coste_unitario', sa.Float(), nullable=False))
    op.add_column('partidas_presupuesto', sa.Column('descuento_porcentaje', sa.Float(), nullable=False))
    op.add_column('partidas_presupuesto', sa.Column('margen_porcentaje', sa.Float(), nullable=False))
    op.alter_column('presupuestos', 'obra_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('presupuestos', 'obra_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('partidas_presupuesto', 'margen_porcentaje')
    op.drop_column('partidas_presupuesto', 'descuento_porcentaje')
    op.drop_column('partidas_presupuesto', 'coste_unitario')
    op.drop_constraint(None, 'capitulos_presupuesto', type_='foreignkey')
    op.drop_column('capitulos_presupuesto', 'padre_id')
    # ### end Alembic commands ###
