"""Add tareas y historial

Revision ID: 93a5248b0adf
Revises: c98529edd4db
Create Date: 2026-08-26 02:52:42.858743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93a5248b0adf'
down_revision: Union[str, None] = 'c98529edd4db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tareas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.Column('visita_id', sa.Integer(), nullable=True),
    sa.Column('creador_id', sa.Integer(), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_limite', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'EN_PROGRESO', 'COMPLETADA', name='estadotarea'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creador_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visita_id'], ['visitas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tareas_obra_id'), 'tareas', ['obra_id'], unique=False)
    op.create_index(op.f('ix_tareas_responsable_id'), 'tareas', ['responsable_id'], unique=False)
    op.create_index(op.f('ix_tareas_visita_id'), 'tareas', ['visita_id'], unique=False)
    op.create_table('tareas_historial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tarea_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('estado_anterior', sa.Enum('PENDIENTE', 'EN_PROGRESO', 'COMPLETADA', name='estadotarea'), nullable=True),
    sa.Column('estado_nuevo', sa.Enum('PENDIENTE', 'EN_PROGRESO', 'COMPLETADA', name='estadotarea'), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tarea_id'], ['tareas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tareas_historial_tarea_id'), 'tareas_historial', ['tarea_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tareas_historial_tarea_id'), table_name='tareas_historial')
    op.drop_table('tareas_historial')
    op.drop_index(op.f('ix_tareas_visita_id'), table_name='tareas')
    op.drop_index(op.f('ix_tareas_responsable_id'), table_name='tareas')
    op.drop_index(op.f('ix_tareas_obra_id'), table_name='tareas')
    op.drop_table('tareas')
    # ### end Alembic commands ###
