"""add eventos and soft delete

Revision ID: 967ddf2dfd0a
Revises: 43da4dd16cc1
Create Date: 2026-09-28 10:50:22.091436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '967ddf2dfd0a'
down_revision: Union[str, None] = '43da4dd16cc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('eventos_actividad',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('tipo_evento', sa.String(length=50), nullable=False),
    # sa.Column('mensaje', sa.String(length=500), nullable=False),
    # sa.Column('empresa_id', sa.Integer(), nullable=False),
    # sa.Column('entidad_relacionada_tipo', sa.String(length=50), nullable=True),
    # sa.Column('entidad_relacionada_id', sa.Integer(), nullable=True),
    # sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    # sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('eventos_actividad_lecturas',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('evento_id', sa.Integer(), nullable=False),
    # sa.Column('usuario_id', sa.Integer(), nullable=False),
    # sa.Column('leido_at', sa.DateTime(timezone=True), nullable=False),
    # sa.ForeignKeyConstraint(['evento_id'], ['eventos_actividad.id'], ondelete='CASCADE'),
    # sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id')
    # )
    op.add_column('empresas', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'is_active')
    op.drop_table('eventos_actividad_lecturas')
    op.drop_table('eventos_actividad')
    # ### end Alembic commands ###
