"""Add lineas medicion

Revision ID: ae103338c776
Revises: 45750f43562b
Create Date: 2026-09-03 15:33:16.205531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae103338c776'
down_revision: Union[str, None] = '45750f43562b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lineas_medicion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.String(length=200), nullable=True),
    sa.Column('unidades', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('longitud', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('anchura', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('altura', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('partida_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['partida_id'], ['partidas_presupuesto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('actividades_cronograma', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_actividades_cronograma_empresa_id'), 'actividades_cronograma', ['empresa_id'], unique=False)
    op.alter_column('certificaciones', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_certificaciones_empresa_id'), 'certificaciones', ['empresa_id'], unique=False)
    op.alter_column('citas_visita', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_citas_visita_empresa_id'), 'citas_visita', ['empresa_id'], unique=False)
    op.alter_column('documentos', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_documentos_empresa_id'), 'documentos', ['empresa_id'], unique=False)
    op.alter_column('eventos_calendario', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_eventos_calendario_empresa_id'), 'eventos_calendario', ['empresa_id'], unique=False)
    op.alter_column('incidencias', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_incidencias_empresa_id'), 'incidencias', ['empresa_id'], unique=False)
    op.alter_column('invitaciones', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('obras', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('presupuestos', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_presupuestos_empresa_id'), 'presupuestos', ['empresa_id'], unique=False)
    op.alter_column('tareas', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_tareas_empresa_id'), 'tareas', ['empresa_id'], unique=False)
    op.drop_constraint(op.f('fk_usuarios_empresa_id'), 'usuarios', type_='foreignkey')
    op.create_foreign_key(None, 'usuarios', 'empresas', ['empresa_id'], ['id'], ondelete='CASCADE')
    op.alter_column('visitas', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_visitas_empresa_id'), 'visitas', ['empresa_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visitas_empresa_id'), table_name='visitas')
    op.alter_column('visitas', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.create_foreign_key(op.f('fk_usuarios_empresa_id'), 'usuarios', 'empresas', ['empresa_id'], ['id'])
    op.drop_index(op.f('ix_tareas_empresa_id'), table_name='tareas')
    op.alter_column('tareas', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_presupuestos_empresa_id'), table_name='presupuestos')
    op.alter_column('presupuestos', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('obras', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('invitaciones', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_incidencias_empresa_id'), table_name='incidencias')
    op.alter_column('incidencias', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_eventos_calendario_empresa_id'), table_name='eventos_calendario')
    op.alter_column('eventos_calendario', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_documentos_empresa_id'), table_name='documentos')
    op.alter_column('documentos', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_citas_visita_empresa_id'), table_name='citas_visita')
    op.alter_column('citas_visita', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_certificaciones_empresa_id'), table_name='certificaciones')
    op.alter_column('certificaciones', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_actividades_cronograma_empresa_id'), table_name='actividades_cronograma')
    op.alter_column('actividades_cronograma', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('lineas_medicion')
    # ### end Alembic commands ###
