"""add_presupuestos_module

Revision ID: c07c89447746
Revises: cfbd0da40ce7
Create Date: 2026-08-28 23:44:17.511378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c07c89447746'
down_revision: Union[str, None] = 'cfbd0da40ce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presupuestos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('iva', sa.Float(), nullable=False),
    sa.Column('estado', sa.Enum('BORRADOR', 'PENDIENTE_APROBACION', 'APROBADO', 'EN_EJECUCION', 'FINALIZADO', 'CANCELADO', name='estadopresupuesto'), nullable=False),
    sa.Column('es_version_activa', sa.Boolean(), nullable=False),
    sa.Column('coste_estimado_obra', sa.Float(), nullable=True),
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.Column('creador_id', sa.Integer(), nullable=True),
    sa.Column('aprobador_id', sa.Integer(), nullable=True),
    sa.Column('fecha_aprobacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aprobador_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creador_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capitulos_presupuesto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('presupuesto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['presupuesto_id'], ['presupuestos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partidas_presupuesto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('capitulo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['capitulo_id'], ['capitulos_presupuesto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('actividades_cronograma', sa.Column('partida_presupuesto_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'actividades_cronograma', 'partidas_presupuesto', ['partida_presupuesto_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'actividades_cronograma', type_='foreignkey')
    op.drop_column('actividades_cronograma', 'partida_presupuesto_id')
    op.drop_table('partidas_presupuesto')
    op.drop_table('capitulos_presupuesto')
    op.drop_table('presupuestos')
    # ### end Alembic commands ###
