"""Add Incidencias

Revision ID: c205cbb622f5
Revises: 525014512f53
Create Date: 2026-08-27 14:38:41.548409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c205cbb622f5'
down_revision: Union[str, None] = '525014512f53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.Column('visita_id', sa.Integer(), nullable=True),
    sa.Column('creador_id', sa.Integer(), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_deteccion', sa.Date(), nullable=False),
    sa.Column('fecha_limite', sa.Date(), nullable=True),
    sa.Column('fecha_resolucion', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('NUEVA', 'EN_PROCESO', 'RESUELTA', 'CERRADA', name='estadoincidencia'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creador_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visita_id'], ['visitas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidencias_codigo'), 'incidencias', ['codigo'], unique=True)
    op.create_index(op.f('ix_incidencias_obra_id'), 'incidencias', ['obra_id'], unique=False)
    op.create_index(op.f('ix_incidencias_responsable_id'), 'incidencias', ['responsable_id'], unique=False)
    op.create_index(op.f('ix_incidencias_visita_id'), 'incidencias', ['visita_id'], unique=False)
    op.create_table('incidencias_archivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incidencia_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('FOTO', 'VIDEO', 'DOCUMENTO', name='tipoarchivoincidencia'), nullable=False),
    sa.Column('nombre_original', sa.String(length=255), nullable=False),
    sa.Column('ruta_archivo', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incidencia_id'], ['incidencias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidencias_archivos_incidencia_id'), 'incidencias_archivos', ['incidencia_id'], unique=False)
    op.create_table('incidencias_historial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incidencia_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('estado_anterior', sa.Enum('NUEVA', 'EN_PROCESO', 'RESUELTA', 'CERRADA', name='estadoincidencia'), nullable=True),
    sa.Column('estado_nuevo', sa.Enum('NUEVA', 'EN_PROCESO', 'RESUELTA', 'CERRADA', name='estadoincidencia'), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incidencia_id'], ['incidencias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidencias_historial_incidencia_id'), 'incidencias_historial', ['incidencia_id'], unique=False)
    op.add_column('tareas', sa.Column('incidencia_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tareas_incidencia_id'), 'tareas', ['incidencia_id'], unique=False)
    op.create_foreign_key(None, 'tareas', 'incidencias', ['incidencia_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tareas', type_='foreignkey')
    op.drop_index(op.f('ix_tareas_incidencia_id'), table_name='tareas')
    op.drop_column('tareas', 'incidencia_id')
    op.drop_index(op.f('ix_incidencias_historial_incidencia_id'), table_name='incidencias_historial')
    op.drop_table('incidencias_historial')
    op.drop_index(op.f('ix_incidencias_archivos_incidencia_id'), table_name='incidencias_archivos')
    op.drop_table('incidencias_archivos')
    op.drop_index(op.f('ix_incidencias_visita_id'), table_name='incidencias')
    op.drop_index(op.f('ix_incidencias_responsable_id'), table_name='incidencias')
    op.drop_index(op.f('ix_incidencias_obra_id'), table_name='incidencias')
    op.drop_index(op.f('ix_incidencias_codigo'), table_name='incidencias')
    op.drop_table('incidencias')
    # ### end Alembic commands ###
