"""add_rol_to_invitacion

Revision ID: c98529edd4db
Revises: a928ada98425
Create Date: 2026-08-26 01:13:04.762189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c98529edd4db'
down_revision: Union[str, None] = 'a928ada98425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        op.add_column('invitaciones', sa.Column('rol', sa.Enum('ADMIN', 'DIRECTOR', 'INSPECTOR', 'LECTOR', name='rolusuario'), server_default=sa.text("'INSPECTOR'::rolusuario"), nullable=False))
    else:
        op.add_column('invitaciones', sa.Column('rol', sa.Enum('ADMIN', 'DIRECTOR', 'INSPECTOR', 'LECTOR', name='rolusuario'), server_default='INSPECTOR', nullable=False))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitaciones', 'rol')
    # ### end Alembic commands ###
