"""add_evento_calendario

Revision ID: cdde6a720902
Revises: c205cbb622f5
Create Date: 2026-08-27 21:14:48.581878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdde6a720902'
down_revision: Union[str, None] = 'c205cbb622f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos_calendario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('HITO', 'REUNION', 'ENTREGA', 'OTRO', name='tipoeventocalendario'), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('obra_id', sa.Integer(), nullable=True),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('creador_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fin', sa.Time(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'COMPLETADO', 'CANCELADO', name='estadoeventocalendario'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creador_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_calendario_fecha'), 'eventos_calendario', ['fecha'], unique=False)
    op.create_index(op.f('ix_eventos_calendario_obra_id'), 'eventos_calendario', ['obra_id'], unique=False)
    op.create_index(op.f('ix_eventos_calendario_responsable_id'), 'eventos_calendario', ['responsable_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eventos_calendario_responsable_id'), table_name='eventos_calendario')
    op.drop_index(op.f('ix_eventos_calendario_obra_id'), table_name='eventos_calendario')
    op.drop_index(op.f('ix_eventos_calendario_fecha'), table_name='eventos_calendario')
    op.drop_table('eventos_calendario')
    # ### end Alembic commands ###
