"""add_actividad_id

Revision ID: cfbd0da40ce7
Revises: f9d6f6be4eb8
Create Date: 2026-08-28 22:15:40.839534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfbd0da40ce7'
down_revision: Union[str, None] = 'f9d6f6be4eb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidencias', sa.Column('actividad_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_incidencias_actividad_id'), 'incidencias', ['actividad_id'], unique=False)
    op.create_foreign_key(None, 'incidencias', 'actividades_cronograma', ['actividad_id'], ['id'], ondelete='SET NULL')
    op.add_column('tareas', sa.Column('actividad_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tareas_actividad_id'), 'tareas', ['actividad_id'], unique=False)
    op.create_foreign_key(None, 'tareas', 'actividades_cronograma', ['actividad_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tareas', type_='foreignkey')
    op.drop_index(op.f('ix_tareas_actividad_id'), table_name='tareas')
    op.drop_column('tareas', 'actividad_id')
    op.drop_constraint(None, 'incidencias', type_='foreignkey')
    op.drop_index(op.f('ix_incidencias_actividad_id'), table_name='incidencias')
    op.drop_column('incidencias', 'actividad_id')
    # ### end Alembic commands ###
