"""add_codigo_cliente_direccion

Revision ID: d00bac3595b1
Revises: 0c69c8c270ab
Create Date: 2026-08-29 10:39:22.946626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd00bac3595b1'
down_revision: Union[str, None] = '0c69c8c270ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presupuestos', sa.Column('codigo', sa.String(length=20), nullable=True))
    op.add_column('presupuestos', sa.Column('cliente_nombre', sa.String(length=200), nullable=True))
    op.add_column('presupuestos', sa.Column('direccion', sa.String(length=200), nullable=True))
    op.add_column('presupuestos', sa.Column('codigo_postal', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_presupuestos_codigo'), 'presupuestos', ['codigo'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_presupuestos_codigo'), table_name='presupuestos')
    op.drop_column('presupuestos', 'codigo_postal')
    op.drop_column('presupuestos', 'direccion')
    op.drop_column('presupuestos', 'cliente_nombre')
    op.drop_column('presupuestos', 'codigo')
    # ### end Alembic commands ###
