"""Add ActividadCronograma

Revision ID: e8e8d3f67d39
Revises: 72d7cc45fd2f
Create Date: 2026-08-28 20:11:30.779728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8e8d3f67d39'
down_revision: Union[str, None] = '72d7cc45fd2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividades_cronograma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin_prevista', sa.Date(), nullable=False),
    sa.Column('fecha_fin_real', sa.Date(), nullable=True),
    sa.Column('porcentaje_avance', sa.Integer(), nullable=False),
    sa.Column('estado_base', sa.Enum('NO_INICIADA', 'EN_EJECUCION', 'COMPLETADA', 'RETRASADA', 'CANCELADA', name='estadoactividad'), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('prioridad', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('es_hito', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actividades_cronograma')
    # ### end Alembic commands ###
