"""Add certificaciones module

Revision ID: f4324ce37e41
Revises: 5a8989b8b7b5
Create Date: 2026-08-29 13:03:36.478027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4324ce37e41'
down_revision: Union[str, None] = '5a8989b8b7b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('presupuesto_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('BORRADOR', 'EMITIDA', 'FACTURADA', 'COBRADA', 'ANULADA', name='estadocertificacion'), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['presupuesto_id'], ['presupuestos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lineas_certificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificacion_id', sa.Integer(), nullable=False),
    sa.Column('partida_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_actual', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['certificacion_id'], ['certificaciones.id'], ),
    sa.ForeignKeyConstraint(['partida_id'], ['partidas_presupuesto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lineas_certificacion')
    op.drop_table('certificaciones')
    # ### end Alembic commands ###
