"""fix_visita_cascade

Revision ID: f9d6f6be4eb8
Revises: e8e8d3f67d39
Create Date: 2026-08-28 21:34:29.382353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9d6f6be4eb8'
down_revision: Union[str, None] = 'e8e8d3f67d39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('incidencias_visita_id_fkey'), 'incidencias', type_='foreignkey')
    op.create_foreign_key(None, 'incidencias', 'visitas', ['visita_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('tareas_visita_id_fkey'), 'tareas', type_='foreignkey')
    op.create_foreign_key(None, 'tareas', 'visitas', ['visita_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tareas', type_='foreignkey')
    op.create_foreign_key(op.f('tareas_visita_id_fkey'), 'tareas', 'visitas', ['visita_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'incidencias', type_='foreignkey')
    op.create_foreign_key(op.f('incidencias_visita_id_fkey'), 'incidencias', 'visitas', ['visita_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
