"""add email verification

Revision ID: fee957102c62
Revises: 967ddf2dfd0a
Create Date: 2026-09-28 11:23:41.179485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fee957102c62'
down_revision: Union[str, None] = '967ddf2dfd0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('email_verificado', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('usuarios', sa.Column('token_verificacion', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'token_verificacion')
    op.drop_column('usuarios', 'email_verificado')
    # ### end Alembic commands ###
